// frontend/qajuda/src/app/views/criaracao/criaracao.component.ts
import { Component, OnInit } from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';
import { Acao } from 'src/app/models/acao';
// import { AcaoService } from 'src/app/services/acao.service';

@Component({
  selector: 'app-criaracao',
  templateUrl: './criaracao.component.html',
  styleUrls: ['./criaracao.component.css']
})
export class CriaracaoComponent {
  acao: Acao = {nome:'', foto:'sem foto', responsavel:'', descricao:'', categoria:'', local:'', data:'', hora:''}
  acoes: Acao[] = [];

  ngOnInitSubmit (acaoForm : NgForm){
    this.acao.nome = acaoForm.value.nome;
    //this.acao.foto = acaoForm.value.foto;
    this.acao.responsavel = acaoForm.value.responsavel;
    this.acao.descricao = acaoForm.value.descricao;
    this.acao.categoria = acaoForm.value.categoria;
    this.acao.local = acaoForm.value.local;
    this.acao.data = acaoForm.value.data;
    this.acao.hora = acaoForm.value.hora;
  }
}

<section class="container">
    <h2>Criar ação de voluntariado</h2>
    <form  #acaoForm="ngForm">
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Nome</label>
            <input type="text" name="nome" class="form-control" id="exampleInputEmail1">
        </div>
        <div>
            <label for="exampleInputEmail1" class="form-label">Tema</label>
            <select name="Tema" class="form-select" aria-label="Default select example">
                <option selected>Escolha um tema</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
              </select>
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Categoria</label>
            <input type="text" name="categoria" class="form-control" id="exampleInputEmail1">
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Local</label>
            <input type="text" name="Local" class="form-control" id="exampleInputEmail1">
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Início</label>
            <input type="text" name="inicio" class="form-control" id="exampleInputEmail1">
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Fim</label>
            <input type="text" name="fim" class="form-control" id="exampleInputEmail1">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Descrição da ação</label>
            <textarea class="form-control" name="descricao" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>
    </form>
</section>

// frontend/v2/src/pages/CriarAcao/index.tsx
import ImageUploadField from "@/components/Dropzone/ImageUploadField";
import Header from "@/components/Header";
import { useForm } from "react-hook-form";

export default function CriarAcao(): JSX.Element {
	const {
		register,
		handleSubmit,
		reset,
		control,
		formState: { errors },
	} = useForm();
	const onSubmit = (data: any) => {
		console.log(data);
		reset();
	};
	return (
		<>
			<Header />
			<div className="container-lg container-md">
				<div className="row m-5 d-flex justify-content-center">
					<div className="col-8">
						<h2 className="mb-5">Criar ação de voluntariado</h2>

						<form onSubmit={handleSubmit(onSubmit)}>
							<div className="row w-100 d-flex justify-content-center g-2 w-75">
								<div className="form-floating col-12">
									<input
										type="text"
										className="form-control"
										placeholder="Digite o nome da ação"
										id="nome"
										{...register("nome")}
									/>
									<label htmlFor="nome">Nome da ação</label>
								</div>
								<div className="form-floating col-12 ">
									<select
										className="form-select"
										id="tema"
										aria-label="Tema da alção"
										defaultValue="#"
										{...register("tema")}
									>
										<option value="#">
											Selecione o tema da ação.
										</option>
										<option value="1">One</option>
										<option value="2">Two</option>
										<option value="3">Three</option>
									</select>
									<label htmlFor="tema">Tema da ação</label>
								</div>
								<div className="form-floating col-12">
									<input
										type="text"
										className="form-control"
										placeholder="Digite a categoria"
										id="categoria"
										{...register("categoria")}
									/>
									<label htmlFor="categoria">Categoria</label>
								</div>
								<div className="form-floating col-12">
									<input
										type="text"
										className="form-control"
										placeholder="Digite o local da ação"
										id="local"
										{...register("local")}
									/>
									<label htmlFor="local">Local</label>
								</div>
								<div className="form-floating col-12">
									<input
										type="datetime-local"
										className="form-control"
										placeholder="Informe a data de início da ação"
										id="inicio"
										{...register("inicio")}
									/>
									<label htmlFor="inicio">
										Início da ação
									</label>
								</div>
								<div className="form-floating col-12">
									<input
										type="datetime-local"
										className="form-control"
										placeholder="Informe a data de fim da ação"
										id="fim"
										{...register("fim")}
									/>
									<label htmlFor="fim">Fim da ação</label>
								</div>
								<div className="form-floating col-12">
									<textarea
										className="form-control"
										placeholder="Informe a descrição da ação"
										id="descricao"
										style={{ height: "100px" }}
										{...register("descricao")}
									></textarea>
									<label htmlFor="descricao">
										Decrição da ação
									</label>
								</div>
								<div className="col-12">
									<ImageUploadField
										placeholder="Clique para selecionar uma imagem."
										control={control}
										name="foto"
									/>
								</div>
								<div className="col-6"></div>
								<div className="col-6 d-grid">
									<button className="btn btn-primary">
										Cadastrar
									</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</>
	);
}
